### ISSUE TITLE
"Network out of sync" crash during multiplayer

### ISSUE THREAD

**Issue by JadedCtrl** [Andrettin/Wyrmgus#114] opened 2017-05-28 16:58 UTC
Using the latest version of Wyrmgus (cloned from GH) on Triquel 6.0 as a server-client, it crashes every time.
On the client side (in Europe), the player can connect-- it works perfectly. Chat and movement are just fine... until a few minutes later when it starts saying it's waiting for the other player (server-client in USA). At this point, chat works still, but movements don't. Then, after that, the player gets gets left alone with an AI on a local game. (When the server crashes)
On the server-client side (in USA), things appear to be pretty OK. Chat works, and movements etc work. But the game keeps saying "Network out of sync da961483!=6bcbea4a! 1648254075!=1770408512! Cycle 4850" or some variation before crashing within a couple of minutes.  
There isn't much to see in the log (it's literally just endless lines of the "Network out of sync" error).

**Comment by Andrettin** [comment] 2017-06-20 07:42
Thanks for the report :) I have recently fixed a network issue that could have been the cause of the problem:
https://github.com/Andrettin/Wyrmgus/commit/3bbf990194944ac245f2e7bd768ea884b8b372c5

The unique item drop code checks if any persistent characters own the unique item already, to see if the item may still drop. This check was also being performed in multiplayer games (which it shouldn't, since persistent hero data will of course vary from player to player), and I've fixed that in the commit I linked to.

**Comment by Andrettin** [comment] 2017-10-13 12:42
With this commit, the issue should be fixed:
https://github.com/Andrettin/Wyrmgus/commit/38e09f964d07efb99268f0bc3021233f24104fa1

**Closed by Andrettin** 2017-10-13 12:42 UTC
