### ISSUE TITLE
5.1.1 does not build

### ISSUE THREAD

**Issue by AMDmi3** [Andrettin/Wyrmgus#176] opened 2021-09-22 02:01 UTC
There are multiple compiler errors. I've patched some of them, but there are more and I guess there's no point to go on unless CI is properly set up upstream.

```
/wrkdirs/usr/ports/games/wyrmgus/work/Wyrmgus-5.1.1/src/util/path_util.h:34:22: error: no viable conversion from 'basic_string<char, char_traits<char>, allocator<char>>' to 'const basic_string<char8_t, char_traits<char8_t>, allocator<char8_t>>'
        const std::u8string u8str = path.u8string();
                            ^       ~~~~~~~~~~~~~~~
```
```
/wrkdirs/usr/ports/games/wyrmgus/work/Wyrmgus-5.1.1/src/script/effect/delayed_effect_instance.cpp:84:18: error: incomplete type 'CPlayer' named in nested name specifier
                        this->scope = CPlayer::Players[scope_index].get();
                                      ^~~~~~~~~
/wrkdirs/usr/ports/games/wyrmgus/work/Wyrmgus-5.1.1/src/script/context.h:29:7: note: forward declaration of 'CPlayer'
class CPlayer;
      ^
In file included from /wrkdirs/usr/ports/games/wyrmgus/work/.build/CMakeFiles/wyrmgus.dir/Unity/unity_script_effect_cxx.cxx:3:
/wrkdirs/usr/ports/games/wyrmgus/work/Wyrmgus-5.1.1/src/script/effect/delayed_effect_instance.cpp:127:37: error: member access into incomplete type 'CPlayer'
                scope = std::to_string(this->scope->get_index());
                                                  ^
```
```
/wrkdirs/usr/ports/games/wyrmgus/work/Wyrmgus-5.1.1/src/ui/interface.cpp:929:41: error: expression is not assignable
                        CPlayer::GetThisPlayer()->get_type() = player_type::computer;
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
In file included from /wrkdirs/usr/ports/games/wyrmgus/work/.build/CMakeFiles/wyrmgus.dir/Unity/unity_ui_cxx.cxx:29:
/wrkdirs/usr/ports/games/wyrmgus/work/Wyrmgus-5.1.1/src/ui/mainscr.cpp:423:48: error: no member named 'Index' in 'CPlayer'; did you mean 'index'?
                        Assert(type.Stats[CPlayer::GetThisPlayer()->Index].Variables[index].Max != 0);
                                                                    ^~~~~
                                                                    index
```

**Comment by Andrettin** [comment] 2021-09-22 09:48
Thanks for the heads up! I can reproduce most of these errors here by building a non-unity or debug build. I've fixed them in the latest commits:
https://github.com/Andrettin/Wyrmgus/commit/4cb1b5815a508ebfb8b769ba70ffb876057a0753
https://github.com/Andrettin/Wyrmgus/commit/d0d17e2604db0dbf8bde4a364fe2b4c85fe4042f
https://github.com/Andrettin/Wyrmgus/commit/af895746da43bb80dee6368dfce93d9f799b0d97

Regarding the very first one in path_util.h, it could be that GCC hasn't updated their std::filesystem::path::u8string() function yet to return an std::u8string instead of an std::string (this is a C++20 change):
https://en.cppreference.com/w/cpp/filesystem/path/string

Either way, just calling std::filesystem::path::string() would be fine there too for Linux, since filepath strings are inherently encoded in UTF-8 under Linux; so this particular issue could be solved via an ifdef.

As for the continuous integration, you are absolutely right, that is something that should be fixed; it stopped working since I updated to SDL2. I will look into creating an updated docker image.

**Comment by AMDmi3** [comment] 2021-09-22 16:15
> Regarding the very first one in path_util.h, it could be that GCC hasn't updated their std::filesystem::path::u8string() function yet to return an std::u8string instead of an std::string (this is a C++20 change):

I use clang/libc++. It doesn't have all C++20 features either.

```
In file included from /wrkdirs/usr/ports/games/wyrmgus/work/.build/CMakeFiles/wyrmgus.dir/cmake_pch.hxx:5:
/wrkdirs/usr/ports/games/wyrmgus/work/Wyrmgus-9655dbc/src/pch.h:57:10: fatal error: 'source_location' file not found
#include <source_location>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by AMDmi3** [comment] 2021-09-22 18:18
I was able to build with these patches: https://github.com/AMDmi3/freebsd-ports/tree/master/games/wyrmgus/files

**Comment by AMDmi3** [comment] 2021-09-22 18:30
It now fails to run:
```
/usr/local/share/wyrmsun/scripts/stratagus.lua:29: main: Stratagus default config file loading ...
/usr/local/share/wyrmsun/scripts/stratagus.lua:1956: main: ... ready!
Wyrmsun v5.1.2, Copyright (c) 1998-2021 by The Stratagus Project
  written by Lutz Sammer, Fabrice Rossi, Vladi Shabanski, Patrice Fortier,
  Jon Gabrielson, Andreas Arens, Nehal Mistry, Jimmy Salmon, Pali Rohar,
  cybermind, Andrettin and others.
	https://github.com/Andrettin/Wyrmgus
Compile options DEBUG ZLIB OPENGL BSD X11 

Stratagus may be copied only under the terms of the GNU General Public License
which may be found in the Stratagus source kit.

DISCLAIMER:
This software is provided as-is.  The author(s) can not be held liable for any
damage that might arise from the use of this software.
Use it at your own risk.

[2021.09.22 21:27:22] File "/home/marakasov/.local/share/Wyrmsun/quests.txt" not found.
[2021.09.22 21:27:22] Invalid interface_style instance: "default".
[2021.09.22 21:27:22] Warning: file:///usr/local/share/wyrmsun/interface/WidgetBase.qml:27:2: QML WidgetImage: Failed to get image from provider: image://interface/default/large_button/normal (file:///usr/local/share/wyrmsun/interface/WidgetBase.qml: 
                                                                          [2021.09.22 21:27:22] Invalid interface_style instance: "default".
[2021.09.22 21:27:22] Warning: file:///usr/local/share/wyrmsun/interface/WidgetBase.qml:27:2: QML WidgetImage: Failed to get image from provider: image://interface/default/large_button/normal (file:///usr/local/share/wyrmsun/interface/WidgetBase.qml: 
                                                                          [2021.09.22 21:27:22] Invalid interface_style instance: "default".
[2021.09.22 21:27:22] Warning: file:///usr/local/share/wyrmsun/interface/WidgetBase.qml:27:2: QML WidgetImage: Failed to get image from provider: image://interface/default/large_button/normal (file:///usr/local/share/wyrmsun/interface/WidgetBase.qml: 
                                                                          [2021.09.22 21:27:22] Invalid interface_style instance: "default".
[2021.09.22 21:27:22] Warning: file:///usr/local/share/wyrmsun/interface/WidgetBase.qml:27:2: QML WidgetImage: Failed to get image from provider: image://interface/default/large_button/normal (file:///usr/local/share/wyrmsun/interface/WidgetBase.qml: 
                                                                          [2021.09.22 21:27:22] Invalid interface_style instance: "default".
[2021.09.22 21:27:22] Warning: file:///usr/local/share/wyrmsun/interface/WidgetBase.qml:27:2: QML WidgetImage: Failed to get image from provider: image://interface/default/large_button/normal (file:///usr/local/share/wyrmsun/interface/WidgetBase.qml: 
                                                                          Thanks for playing Wyrmsun.
[2021.09.22 21:27:22] Invalid interface_style instance: "default".
[2021.09.22 21:27:22] Warning: file:///usr/local/share/wyrmsun/interface/WidgetBase.qml:27:2: QML WidgetImage: Failed to get image from provider: image://interface/default/large_button/normal (file:///usr/local/share/wyrmsun/interface/WidgetBase.qml: 
                                                                          [2021.09.22 21:27:22] Invalid interface_style instance: "default".
[2021.09.22 21:27:22] Warning: file:///usr/local/share/wyrmsun/interface/WidgetBase.qml:27:2: QML WidgetImage: Failed to get image from provider: image://interface/default/large_button/normal (file:///usr/local/share/wyrmsun/interface/WidgetBase.qml: 
                                                                          [2021.09.22 21:27:22] Invalid interface_style instance: "default".
[2021.09.22 21:27:22] Warning: file:///usr/local/share/wyrmsun/interface/WidgetBase.qml:27:2: QML WidgetImage: Failed to get image from provider: image://interface/default/large_button/normal (file:///usr/local/share/wyrmsun/interface/WidgetBase.qml: 
```
I remember that with 5.0.1 I've had to add some qt dependencies like quickcontrols quickcontrols2 and graphicaleffects which were not listed anywhere in the docs or build system and were not checked during the build. May it be that some more of them are now required?

**Comment by Andrettin** [comment] 2021-09-22 20:09
Thanks for the error report! The actual error has to do with changes to persistent quest completion saving (the rest are just subsequent errors due to the database not having been initialized properly). I've fixed the issue here now:
https://github.com/Andrettin/Wyrmgus/commit/38bed6a80c76519ddfc90d35328aad9a662fd8bd

**Comment by Andrettin** [comment] 2021-09-22 20:15
> 
> 
> I was able to build with these patches: https://github.com/AMDmi3/freebsd-ports/tree/master/games/wyrmgus/files

Thanks! I think those changes would be good to add to the source code under a Clang ifdef. Checking for the __clang__ seems to be the appropriate way to do it, from what I've gathered. Or do you have a different suggestion?

**Comment by Andrettin** [comment] 2021-09-22 20:27
I've gone ahead and committed those changes:
https://github.com/Andrettin/Wyrmgus/commit/59abd7279de1bf6a4d001d78bdbb9e6050b1d4d2

If you think a different macro would be better, let me know!

**Comment by AMDmi3** [comment] 2021-09-22 20:27
For my specific case it should probably check for libc++ version, I'll try to come with proper ifdefs. However, shouldn't it be more like #ifdef WIN32 or __linux__  as, like you've said, linux (BSD and probably other *nix like OSes) should have paths utf8 encoded by default. I'm particularly suspicious towards the last function, utf16 is likely not suitable for *nix at all.

**Comment by Andrettin** [comment] 2021-09-22 20:34
> 
> 
> For my specific case it should probably check for libc++ version, I'll try to come with proper ifdefs. However, shouldn't it be more like #ifdef WIN32 or **linux** as, like you've said, linux (BSD and probably other *nix like OSes) should have paths utf8 encoded by default. I'm particularly suspicious towards the last function, utf16 is likely not suitable for *nix at all.

Yes, for the last function I've checked for Windows instead. The C++ standard itself allows for std::filesystem::path to be constructed from an std::u16string:
https://en.cppreference.com/w/cpp/filesystem/path/path

So in principle the previous code would have been platform-independent, if each platform implemented the standard perfectly. Nevertheless, it is weird, yes, (and probably inefficient) to construct a filepath from a UTF-16 string in Unix.

For the other functions, I think that in principle it would be better to have platform-independent code that ensures that the filepaths are UTF-8 encoded; the ifdefs would be more of a stopgap until all major compilers fully implement C++20.

**Comment by Andrettin** [comment] 2021-09-25 19:21
Good news: I got the CI working again! Thanks to the documentation written by @bergentroll in the README_ACTIONS.md file, I was able to create an updated docker image, with the SDL2 library change taken into account.

**Comment by AMDmi3** [comment] 2021-09-28 16:47
It builds and runs now. However, pressing a button to start a scenario or a legacy quest doesn't do anything, e.g. game does not start. No messages on console either.

**Closed** 2021-09-28 16:50 UTC
